# Exploratory Data Analysis and Insights on the Iris Dataset Using Pandas

### Beginner-to-Intermediate Pandas Practice Notebook

This notebook is designed for students who know the basics of Python and are learning how to explore data with **Pandas**.

The exercises begin with simple DataFrame operations and gradually introduce:

- Loading and inspecting a CSV file
- Checking missing and duplicate values
- Selecting rows and columns
- Calculating descriptive statistics
- Filtering and sorting records
- Grouping and aggregating data
- Creating new columns
- Finding correlations
- Creating basic visualizations
- Exporting a DataFrame

## About the Dataset

The **Iris.csv** dataset contains measurements for **150 iris flowers** belonging to three species.

It contains **5 columns**:

| Column | Description |
|---|---|
| `sepal_length` | Sepal length in centimetres |
| `sepal_width` | Sepal width in centimetres |
| `petal_length` | Petal length in centimetres |
| `petal_width` | Petal width in centimetres |
| `species` | Iris species: setosa, versicolor, or virginica |

The dataset has no standard missing values. Because it contains both numerical measurements and a categorical species column, it is useful for practicing data inspection, filtering, grouping, aggregation, and visualization.

**Original dataset:** [UCI Machine Learning Repository](https://archive.ics.uci.edu/dataset/53/iris)  
**CSV source:** [seaborn-data](https://github.com/mwaskom/seaborn-data/blob/master/iris.csv)

## Learning Goal

By completing this assignment, you will move from basic Pandas operations to simple intermediate analysis. You will compare flower species, create derived measurements, examine relationships between numeric columns, and present results with basic charts.

## 1. Loading and Understanding the Dataset

### Question 1
Import the Pandas library using the alias `pd` and read **Iris.csv** into a DataFrame named `df`.

In [1]:
import pandas as pd

df=pd.read_csv("../Datasets/Iris.csv")
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

### Question 2
Display the first **5 rows** of the dataset.

In [2]:
df.head(5)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

### Question 3
Display the last **5 rows** of the dataset.

In [3]:
df.tail()

     sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

### Question 4
Find the total number of **rows and columns** in the dataset.

In [6]:
df.shape

(150, 5)

### Question 5
Display all the **column names** in the dataset.

In [9]:
col_names=list(df.columns)
print(col_names)

['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']

### Question 6
Display the **data type of each column**.

In [14]:
# col_data_types=dict(df.dtypes)
# print(col_data_types)
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species             str
dtype: object

### Question 7
Display a complete summary of the DataFrame using `info()`.

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

## 2. Checking Data Quality

### Question 8
Check the number of **missing values in each column**.

In [19]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

### Question 9
Check whether the dataset contains any **duplicate rows** and display the total number of duplicates.

In [25]:
print(df.duplicated().any())
print(df.duplicated().sum())
print(df.shape)

True
1
(150, 5)

### Question 10
Create a new DataFrame named `df_clean` with duplicate rows removed. Then display its shape.

### Question 11
Confirm that `df_clean` contains no duplicate rows.

## 3. Selecting Rows and Columns

### Question 12
Select and display only the **species** column from `df`.

### Question 13
Select and display the four measurement columns: **sepal_length, sepal_width, petal_length, and petal_width**.

### Question 14
Display the first **10 rows** using DataFrame slicing.

### Question 15
Using `iloc`, display the first **5 rows and first 3 columns**.

### Question 16
Using `loc`, display rows **10 to 15** for the columns **sepal_length, petal_length, and species**.

## 4. Descriptive Statistics and Species Values

### Question 17
Display descriptive statistics for all **numeric columns** using `describe()`.

### Question 18
Calculate the **mean sepal length** of all flowers.

### Question 19
Find the **minimum and maximum petal width** in the dataset.

### Question 20
Display all the **unique species names** in the dataset.

### Question 21
Count the number of flowers belonging to each species using `value_counts()`.

## 5. Filtering and Sorting

### Question 22
Display all flowers whose **sepal_length is greater than 6.0 cm**.

### Question 23
Display only the flowers belonging to the **setosa** species.

### Question 24
Display all **versicolor** flowers whose **petal_length is greater than 4.0 cm**.

### Question 25
Using `query()`, display flowers whose **petal_width is greater than 1.5 cm** and **sepal_width is greater than 3.0 cm**.

### Question 26
Sort the dataset by **sepal_length in descending order** and display the first 10 rows.

### Question 27
Display the **5 flowers with the greatest petal_length**.

## 6. Grouping and Aggregation

### Question 28
Group the dataset by **species** and calculate the mean of every numeric column.

### Question 29
Calculate the **average sepal_length for each species**.

### Question 30
For each species, calculate the **minimum and maximum petal_length** using `agg()`.

### Question 31
Calculate the **median petal_width for each species**.

### Question 32
Determine which species has the **highest average petal_width**.

## 7. Creating and Modifying Columns

### Question 33
Create a new column named **sepal_area** by multiplying `sepal_length` by `sepal_width`.

### Question 34
Create a new column named **petal_area** by multiplying `petal_length` by `petal_width`.

### Question 35
Create a column named **sepal_size** using `apply()` with a `lambda` function. Store `Large` when `sepal_length` is greater than or equal to 5.8; otherwise store `Small`.

### Question 36
Rename the column **species** to **flower_species** in a new DataFrame named `df_renamed`.

## 8. Correlation, Visualization, and Export

### Question 37
Create and display a **correlation matrix** for the numeric columns.

### Question 38
Create a **histogram** of the `sepal_length` column with an appropriate title and axis labels.

### Question 39
Create a **bar chart** showing the average `petal_length` for each species.

### Question 40
Create a **box plot** comparing `petal_length` across the three species.

### Question 41
Save the final DataFrame as **Iris_Practice_Output.csv** using `to_csv()` without saving the index.

## End of Practice

Try to solve each question independently before checking any reference material.

The main goal is to become comfortable with a complete beginner-to-intermediate Pandas workflow: loading data, checking its quality, exploring values, comparing groups, creating useful columns, visualizing results, and exporting the final DataFrame.